Add BUCKET_INTERNAL_INGEST as a container parameter
mozilla/prio-processor pull request #115
Opened 2021-04-23 02:27 UTC by acmiyaguchi

This fixes #102 and allows for cleaner semantics between the use of each bucket.

2021-04-26 21:59 UTC, acmiyaguchi commented
A lot of this is duplicated from #113, with `admin` now being referred to as `ingest` and the addition of a new bucket to separate concerns.

2021-04-26 22:02 UTC, acmiyaguchi commented on deployment/testing-v4/terraform/main.tf
> +}
In my opinion, this is the ugliest part of this configuration. However, this makes the relationship explicit. The ingest server also has more permissions than would be specified here, like access to shared-prod and the like.

2021-04-27 16:02 UTC, wlach requested changes
I *think* I understand what you're doing here, but it's not 100% clear. Shouldn't you update  https://github.com/mozilla/prio-processor/blob/main/docs/guide.md as well? Doing so will have the side benefit of making this PR easier to review.

2021-04-27 18:27 UTC, acmiyaguchi commented
I've updated the documentation to reflect the new variables. Some of those sections will require a little bit of rework, but I'll do my best to update the docs to reflect any changes I'm making now. It's nice to have a skeleton to work on.

2021-04-27 18:36 UTC, wlach approved these changes

2021-04-27 18:37 UTC, merged